services:
  redis:
    image: redis:7.4.9
    container_name: mall-redis
    command: redis-server --maxmemory 128mb --maxmemory-policy volatile-lru
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    restart: unless-stopped

  nacos:
    image: nacos/nacos-server:v3.2.1
    container_name: mall-nacos
    ports:
      - "8847:8080"   # 控制台 UI（映射到容器内的 8080）
      - "8848:8848"   # API（微服务连接，不用改）
      - "9848:9848"   # gRPC
    environment:
      MODE: standalone
      SPRING_DATASOURCE_PLATFORM: "mysql"
      NACOS_AUTH_TOKEN: "VGhpc0lzTXlDdXN0b21TZWNyZXRLZXkwMTIzNDU2Nzg="
      NACOS_AUTH_IDENTITY_KEY: "nacos"
      NACOS_AUTH_IDENTITY_VALUE: "nacos"
      JVM_XMS: 256m
      JVM_XMX: 256m
      JVM_XMN: 128m
      # MySQL 连接（你的 MySQL 在 Windows 宿主机上）
      MYSQL_SERVICE_HOST: mall-mysql
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_DB_NAME: ry-config
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: "138992"
      MYSQL_SERVICE_DB_PARAM: characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:9.2.5
    container_name: mall-es
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    volumes:
      - ./data/es:/usr/share/elasticsearch/data
      - ./data/es/plugins/ik:/usr/share/elasticsearch/plugins/ik
    restart: unless-stopped

  sentinel-dashboard:
    image: bladex/sentinel-dashboard:1.8.8
    container_name: mall-sentinel
    ports:
      - "8718:8858"
    environment:
      JAVA_OPTS: "-Xms128m -Xmx128m"
    restart: unless-stopped

  rocketmq:
    image: apache/rocketmq:5.5.0
    container_name: mall-rmq
    entrypoint: |
      sh -c "
      nohup sh mqnamesrv > /tmp/namesrv.log 2>&1 &
      sleep 5
      sh mqbroker -n localhost:9876 --enable-proxy
      "
    ports:
      - "9876:9876"    # NameServer
      - "10911:10911"   # Broker
      - "10909:10909"   # gRPC Proxy（5.x 自带）
    environment:
      JAVA_OPT_EXT: "-Xms128m -Xmx256m"
    volumes:
      - ./data/rocketmq/logs:/home/rocketmq/logs
      - ./data/rocketmq/store:/home/rocketmq/store
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mall-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "138992"
      TZ: Asia/Shanghai
    command: --innodb_buffer_pool_size=128M
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: unless-stopped
volumes: {}